CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node=8 lora_finetune.py \
    --model_path microsoft/VibeVoice-ASR \
    --data_dir ./Train \
    --output_dir ./output \
    --num_train_epochs 100 \
    --lora_r 8 \
    --lora_alpha 32 \
    --lora_dropout 0.05 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --learning_rate 1e-5 \
    --warmup_ratio 0.1 \
    --weight_decay 0.01 \
    --max_grad_norm 1.0 \
    --logging_steps 1 \
    --gradient_checkpointing \
    --bf16 \
    --report_to none